// Generated by CoffeeScript 2.7.0
var defaultCode, editor, editorJar, errorBox, highlight, initialSourceCode, onShare, onUpdate, preview, previewJar, shareButton, withoutHash;

import {
  CodeJar
} from "https://medv.io/codejar/codejar.js";

import {
  compile
} from "https://esm.sh/@danielx/civet";

import Prism from "https://cdn.skypack.dev/prismjs";

defaultCode = `sum := (a:number, b:number) => a + b
square := (a:number) => a * a

fun := -> 
  console.log "It's all fun and games till it breaks"

song := ["do", "re", "mi", "fa", "so"]

singers := {Jagger: "Rock", Elvis: "Roll"}

bitlist := [
  1, 0, 1
  0, 0, 1
  1, 1, 0
];


// hey jsx dudes... here
Component := () => <>{bitlist.map (x) => <p>x</p> }</>`;

editor = document.getElementById("editor");

preview = document.getElementById("preview");

errorBox = document.getElementById("error-box");

shareButton = document.getElementById("share-btn");

initialSourceCode = defaultCode;

if (window.location.hash) {
  withoutHash = window.location.hash.trim().replace(/^#/, "");
  initialSourceCode = atob(withoutHash);
}

highlight = function(c) {
  var out;
  out = Prism.highlight(c.innerText, Prism.languages.javascript, "javascript");
  return c.innerHTML = out;
};

previewJar = CodeJar(preview, highlight, {
  tab: " ".repeat(2)
});

editorJar = CodeJar(editor, function() {}, {
  tab: " ".repeat(2)
});

onUpdate = function(c) {
  var browserCompile, err;
  try {
    browserCompile = compile(c);
    previewJar.updateCode(browserCompile);
    return errorBox.innerText = "";
  } catch (error) {
    err = error;
    return errorBox.innerText = err.message;
  }
};

editorJar.onUpdate(onUpdate);

editorJar.updateCode(initialSourceCode);

previewJar.updateCode(compile(initialSourceCode));

onShare = function() {
  var base64, code;
  code = editorJar.toString();
  base64 = btoa(code);
  window.location.hash = base64;
  return copyToClipboard(window.location.href);
};

shareButton.addEventListener("click", onShare);
